### ISSUE TITLE
Add signin and signup pages in frontend

### ISSUE THREAD

**Issue by ankitjoshi14** [ayushjoshi165/TuesdayDotCom#1]
Add sign in and sign up pages in frontend. 

- Use bootstrap css for all.

**Comment by ankitjoshi14** [comment]
DO not merge to master. Create a new branch same as issue no. for example "issue1_signinsignupfront"

**Comment by ayushjoshi165** [comment]
I have added the login and signup page in the master branch and just added a comment in the new branch name feature

**Comment by ayushjoshi165** [comment]
Added changes
