### ISSUE TITLE
Add EsLint and Airbnb stype guide in front end

### ISSUE THREAD

**Issue by ankitjoshi14** [ayushjoshi165/TuesdayDotCom#2]
https://www.youtube.com/watch?v=SydnKbGc7W8
Watch this. and install
again new branch - "issue2_addeslint"

**Comment by ayushjoshi165** [comment]
Create new branch issue2_addeslint, added the eslint, prettier and airbnb style guide and created a pull request

**Comment by ayushjoshi165** [comment]
[issue2_addeslint](https://github.com/ayushjoshi165/TuesdayDotCom/pulls)

**Comment by ankitjoshi14** [comment]
Fix the eslint. and comment on config

**Comment by ayushjoshi165** [comment]
Fixed the eslint issue and followed thr Airbnb rule : https://github.com/ayushjoshi165/TuesdayDotCom/pull/3

**Comment by ankitjoshi14** [comment]
LGTM , you can close the issue and merge the changes
